name: pretty-list-routes
description: ğŸ›£ï¸ A beautiful `list:routes` for AdonisJS
repo: Julien-R44/pretty-list-routes
npm: pretty-list-routes
icon: ''
github: https://github.com/Julien-R44/pretty-list-routes
website: https://github.com/Julien-R44/pretty-list-routes
learn_more: ''
category: Devtools
type: 3rd-party
maintainers:
  - name: Julien-R44
    github: Julien-R44
