name: swagger
description: Swagger provider for AdonisJS 5
repo: reg2005/adonis5-swagger
npm: adonis5-swagger
icon: swagger.png
github: https://github.com/reg2005/adonis5-swagger
website: https://github.com/reg2005/adonis5-swagger
learn_more: ''
category: Devtools
type: 3rd-party
maintainers:
  - name: reg2005
    github: reg2005
compatibility:
  nuxt: ^2.0.0
  requires: {}
